openapi: 3.1.0
info:
  title: Sticker Micro-Business API
  description: API Specs for the Sticker Micro-Business application
  version: 0.1.0


servers:
  - url: http://localhost:8080/v1
    description: Local dev server for the API version 1.


components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          format: int32
        email:
          type: string
        stagingArea:
          $ref: "#/components/schemas/StagingArea"

    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string

    Category:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        stickers:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/Sticker"

    Order:
      type: object
      properties:
        id:
          type: integer
          format: int32
        customerId:
          type: integer
          format: int32
        placementTimestamp:
          type: string
          format: date-time
          description: Order placement time as an RFC 3339 date-time.
        status:
          $ref: "#/components/schemas/OrderStatus"
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
    
    OrderStatus:
      type: string
      enum:
        - SUBMITTED
        - ACCEPTED
        - DENIED
        - IN_PROGRESS
        - PRINTED
        - SHIPPED
        - CANCELED

    OrderItem:
      type: object
      properties:
        id:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
        sheet:
          $ref: "#/components/schemas/StickerSheet"

    StagingArea:
      type: object
      properties:
        id: 
          type: integer
          format: int32
        selections:
          type: array
          items:
            $ref: "#/components/schemas/StickerSelection"

    Sticker:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 123
        name:
          type: string
          example: "my sticker"
        designPath:
          type: string
          example: "./sticker-library/stickers/mySticker.svg"
          description: Path or URL used to retrieve the sticker design.
        physicalWidth:
          type: number
          format: double
          example: 123.56
          description: Physical width of the stickers in inches.
        physicalHeight:
          type: number
          format: double
          example: 123.56
          description: Physical height of the stickers in inches.
        borderThickness:
          type: number
          format: double
          example: 123.56
          description: The border thickness (margin) of the sticker.
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
          description: An array of tags associated with the sticker.

    StickerSelection:
      type: object
      properties:
        id:
          type: integer
          format: int32
        sticker:
          $ref: "#/components/schemas/Sticker"
        quantity:
          type: integer
          format: int32
          description: The quantity of a single type of sticker in a sticker selection.

    StickerSheet:
      type: object
      properties:
        id:
          type: integer
          format: int32
        price:
          type: number
          format: double
          description: The price of the sticker sheet in USD.
        pdfPath:
          type: string
          description: The path to the PDF file of the sticker sheet.
        hpglPath:
          type: string
          description: The path to the HPGL file of the sticker sheet.
        width:
          type: number
          format: double
          description: The width of the sticker sheet in inches.
        height:
          type: number
          format: double
          description: The height of the sticker sheet in inches.

paths:
  /stickers:
    get:
      summary: Returns a list of all stickers the admin uploaded.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: List of stickers uploaded by the admin.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sticker"
              example:
                - id: 123
                  name: "my sticker"
                  designPath: "./sticker-library/stickers/mySticker.svg"
                  physicalWidth: 3.5
                  physicalHeight: 2.0
                  borderThickness: 0.125
                  tags:
                    - id: 7
                      name: "animals"

  /stickers/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: ID of the sticker.
        schema:
          type: integer
          format: int32
        example: 123
    get:
      summary: Returns the sticker associated with that ID.
      responses:
        "200":
          description: The requested sticker.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sticker"
              example:
                id: 123
                name: "my sticker"
                designPath: "./sticker-library/stickers/mySticker.svg"
                physicalWidth: 3.5
                physicalHeight: 2.0
                borderThickness: 0.125
                tags:
                  - id: 7
                    name: "animals"
    put:
      summary: Modify an existing sticker.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sticker"
            example:
              id: 123
              name: "my sticker"
              designPath: "./sticker-library/stickers/mySticker.svg"
              physicalWidth: 3.5
              physicalHeight: 2.0
              borderThickness: 0.125
              tags:
                - id: 7
                  name: "animals"
      responses:
        "200":
          description: The updated sticker.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sticker"
              example:
                id: 123
                name: "my sticker"
                designPath: "./sticker-library/stickers/mySticker.svg"
                physicalWidth: 3.5
                physicalHeight: 2.0
                borderThickness: 0.125
                tags:
                  - id: 7
                    name: "animals"
    delete:
      summary: Delete an existing sticker.
      responses:
        "204":
          description: Sticker deleted.

  /stickers/upload:
    post:
      summary: Upload a sticker.

  /stickers-display:
    get:
      summary: Returns the list of stickers viewable by the customers.

  /sticker-display/{id}:
    post:
      summary: Make a sticker viewable for the customers.

  /categories:
    get:
      summary: Get all categories
    post:
      summary: Create a category.

  /categories/{id}:
    get:
      summary: Get the category associated with that ID.
    put:
      summary: Modify an existing category.

  /staging-area:
    get:
      summary: Get the staging area of the user with the given user ID.
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get.
  /staging-area/items:
    post:
      summary: Add a sticker to the staging area.
  /staging-area/items/{stickerSelectionId}:
    put:
      summary: Change the quantity of stickers in a sticker selection.
    delete:
      summary: Delete the sticker selection.
  /staging-area/generate:
    post:
      summary: Generate the sticker sheet preview.

  /cart:
    get:
      summary: Get the cart of the user with the given user ID.
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get.
  /cart/items:
    post:
      summary: Add a sticker sheet to the cart.
  /cart/items/{cartItemId}:
    put:
      summary: Change the quantity of stickersheet in a cart item.
    delete:
      summary: Delete a cart item.
  /cart/checkout:
    post:
      summary: Checkout the cart.

  /orders:
    get:
      summary: Get all the orders of the admin.
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get.
  /orders/{orderId}:
    get:
      summary: Get the order associated with that ID.
    patch:
      summary: Update the status of the order.
